add width/height to /screenshot POST request
devtomio/website-screenshot pull request #38
Opened 2022-06-17 23:07 UTC by luroc

As requested in #37 

This is probably a quite naive implementation, as I have next to no experience with Rust, but it works for me so far.

2022-06-18 03:58 UTC, devtomio commented on src/routes/screenshot.rs
> +    let height = payload.height;
```suggestion
```

2022-06-18 03:59 UTC, devtomio requested changes
a few nits

2022-06-18 03:59 UTC, devtomio commented on src/routes/screenshot.rs
> +    client.set_window_size(width, height).await.expect("Failed setting window size");
```suggestion
    client.set_window_size(payload.width, payload.height).await.expect("Failed setting window size");
```

2022-06-18 03:59 UTC, devtomio commented on src/routes/screenshot.rs
> +    let height = payload.height;
```suggestion
```

2022-06-18 03:59 UTC, devtomio commented on src/routes/screenshot.rs
> +    client.set_window_size(width, height).await.expect("Failed setting window size");
just set it on the function

2022-06-18 20:29 UTC, luroc commented
Looks good to me (but what do I know ;) )

Mind also that your default was 1980x1080 and I changed that to 1920x1080, in case you missed that and the 1980 had a specific reason.

2022-06-19 03:59 UTC, devtomio approved these changes

2022-06-19 03:59 UTC, merged